SELECT A.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    ) A
JOIN REST_INFO I 
ON A.MAX = I.FAVORITES AND A.FOOD_TYPE = I.FOOD_TYPE
ORDER BY A.FOOD_TYPE DESC;