SELECT B.ID, C.FISH_NAME, A.M AS LENGTH
FROM (
    SELECT FISH_TYPE, MAX(LENGTH) AS M
    FROM FISH_INFO
    GROUP BY FISH_TYPE) A, FISH_INFO B, FISH_NAME_INFO C
WHERE A.FISH_TYPE = B.FISH_TYPE 
    AND A.FISH_TYPE = C.FISH_TYPE
    AND A.M = B.LENGTH;
    
SELECT ID, FISH_NAME, LENGTH
FROM (SELECT *
FROM (
    SELECT FISH_TYPE AS F, MAX(LENGTH) AS M
    FROM FISH_INFO
    GROUP BY FISH_TYPE) A, FISH_INFO B
WHERE A.F = B.FISH_TYPE 
    AND A.M = B.LENGTH) C
JOIN FISH_NAME_INFO I 
ON C.FISH_TYPE = I.FISH_TYPE
    
