WITH A AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
)

SELECT SCORE, A.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM A
JOIN HR_EMPLOYEES E
ON A.EMP_NO = E.EMP_NO
WHERE SCORE = (
    SELECT MAX(SCORE)
    FROM A
)