-- 코드를 작성해주세요
SELECT SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM (
    SELECT EMP_NO AS NUMBER, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
) A
JOIN HR_EMPLOYEES H 
ON H.EMP_NO = A.NUMBER
ORDER BY SCORE DESC
LIMIT 1;

   